# conda env create -f requirements-cpu.yml
name: ctlearn
channels:
    - conda-forge
    - menpo
dependencies:
    - python=3.6.5
    - matplotlib
    - numpy
    - astropy
    - opencv
    - pillow
    - pip
    # TensorFlow-CPU v1.12.0:
    - pip:
        - https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.12.0-cp36-cp36m-win_amd64.whl
    - pytables
    - pyyaml
    - scikit-learn
    - scipy
