# conda env create -f environment-gpu.yml
name: ctlearn
channels:
    - conda-forge
    - menpo
dependencies:
    - python=3.6.5
    - matplotlib
    - numpy
    - astropy
    - opencv
    - pillow
    - pip
    # Install tensorflow-gpu via conda
    - tensorflow-gpu=1.12.0
    - pytables
    - pyyaml
    - scikit-learn
    - scipy
